#version: '3.9'

services:
  # PostgreSQL database service
  db:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Scraper service (Telegram data ingestion)
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-scraper
    env_file: .env
    depends_on:
      - db
    command: [ "python", "telegram_scraper/main.py" ]

  # API service (exposes data via FastAPI)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-api
    env_file: .env
    depends_on:
      - db
    command: [ "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000" ]
    ports:
      - "8000:8000"

volumes:
  pgdata:
